version: '3'
services:
  db:
    image: mysql:8
    networks:
    - bridge
    environment:
      - MYSQL_ROOT_PASSWORD=detest
      - MYSQL_DATABASE=detest
      - MYSQL_USER=detest
      - MYSQL_PASSWORD=detest
    ports:
      - '3306:3306'

networks:
  bridge:
    name: webnet
    external: true
